---
abstract: 'Easily create test classes in an xUnit/JUnit style'
author:
  - 'Adrian Howard <adrianh@quietstars.com>, Curtis "Ovid" Poe, <ovid at cpan.org>, Mark Morgan <makk384@gmail.com>.'
build_requires:
  Fcntl: '0'
  IO::File: '1.09'
  Test: '0'
  Test::Exception: '0.25'
  Test::More: '0.78'
  base: '0'
  overload: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Class
provides:
  Test::Class:
    file: lib/Test/Class.pm
    version: '0.48'
  Test::Class::Load:
    file: lib/Test/Class/Load.pm
    version: '0.48'
  Test::Class::MethodInfo:
    file: lib/Test/Class/MethodInfo.pm
    version: '0.48'
requires:
  Attribute::Handlers: '0.77'
  Carp: '0'
  File::Find: '0'
  File::Spec: '0'
  MRO::Compat: '0.11'
  Module::Runtime: '0'
  Storable: '2.04'
  Test::Builder: '0.78'
  Test::Builder::Tester: '1.02'
  Test::Simple: '1.001002'
  Try::Tiny: '0'
  constant: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/adrianh/test-class/
version: '0.48'
