---
abstract: 'Easily create test classes in an xUnit/JUnit style'
author:
  - "Adrian Howard <adrianh@quietstars.com>, Curtis \"Ovid\" Poe, <ovid at cpan.org>, Mark Morgan <makk384@gmail.com>."
build_requires:
  IO::File: 1.09
  Test::Exception: 0.25
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Class
provides:
  Test::Class:
    file: lib/Test/Class.pm
    version: 0.37
  Test::Class::Load:
    file: lib/Test/Class/Load.pm
    version: 0.35
  Test::Class::MethodInfo:
    file: lib/Test/Class/MethodInfo.pm
    version: 0.34
requires:
  Attribute::Handlers: 0.77
  MRO::Compat: 0.11
  Storable: 2.04
  Test::Builder: 0.78
  Test::Builder::Tester: 1.02
  Test::More: 0.78
  Test::Simple: 0.78
  perl: 5.006001
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/adrianh/test-class/
version: 0.37
