# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Class
version:      0.06_2
version_from: lib/Test/Class.pm
installdirs:  site
requires:
    Attribute::Handlers:           0.77
    Class::ISA:                    0.32
    Devel::Symdump:                2.03
    IO::File:                      1.08
    Storable:                      2.04
    Test::Builder:                 0.16
    Test::Builder::Tester:         0.09
    Test::Differences:             0.43
    Test::Exception:               0.1
    Test::More:                    0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
