--- #YAML:1.0
name: Test-Class
version: 0.07
author: ~
abstract: ~
license: perl
requires:
  perl: 5.6.1
build_requires:
  Attribute::Handlers: 0.77
  Class::ISA: 0.32
  Devel::Symdump: 2.03
  Storable: 2.04
  Test::Builder: 0.16
  Test::Builder::Tester: 1.01
  Test::Differences: 0.43
  Test::Exception: 0.10
  Test::More: 0.44
provides:
  Test::Class:
    file: lib/Test/Class.pm
    version: 0.07
  Test::Class::MethodInfo:
    file: lib/Test/Class/MethodInfo.pm
    version: 0.01
generated_by: Module::Build version 0.2604
